### ISSUE TITLE
problem with finetuning 

### ISSUE THREAD

**Issue by kattens** [nadavbra/protein_bert#56]
hello,
I have been trying to run the example given in this notebook ( https://github.com/nadavbra/protein_bert/blob/master/ProteinBERT%20demo.ipynb ). however, when the model tried to fine-tune and run for 40 epochs, after 3 epochs, this error happened: 
AttributeError                            Traceback (most recent call last)

[<ipython-input-15-c065300db32e>](https://localhost:8080/#) in <cell line: 1>()
----> 1 finetune(model_generator, input_encoder, OUTPUT_SPEC, train_set['seq'], train_set['label'], valid_set['seq'], valid_set['label'], \
      2         seq_len = 512, batch_size = 32, max_epochs_per_stage = 10, lr = 1e-04, begin_with_frozen_pretrained_layers = True, \
      3         lr_with_frozen_pretrained_layers = 1e-02, n_final_epochs = 1, final_seq_len = 1024, final_lr = 1e-05, callbacks = training_callbacks)

2 frames

[/usr/local/lib/python3.10/dist-packages/proteinbert/model_generation.py](https://localhost:8080/#) in update_state(self, model)
     33     def update_state(self, model):
     34         self.model_weights = copy_weights(model.get_weights())
---> 35         self.optimizer_weights = copy_weights(model.optimizer.get_weights())
     36 
     37     def _init_weights(self, model):

AttributeError: 'Adam' object has no attribute 'get_weights'

I tried to uninstall and reinstall my Tensorflow to an older version, But again, after a couple of epochs, this error happened:
Epoch 1/10
468/468 [==============================] - ETA: 0s - loss: 0.0998

WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.

468/468 [==============================] - 1594s 3s/step - loss: 0.0998 - val_loss: 0.0641 - lr: 0.0100
Epoch 2/10
468/468 [==============================] - ETA: 0s - loss: 0.0741

WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.

468/468 [==============================] - 1597s 3s/step - loss: 0.0741 - val_loss: 0.0635 - lr: 0.0100
Epoch 3/10
468/468 [==============================] - ETA: 0s - loss: 0.0735

WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.

Epoch 3: ReduceLROnPlateau reducing learning rate to 0.0024999999441206455.
468/468 [==============================] - 1568s 3s/step - loss: 0.0735 - val_loss: 0.1107 - lr: 0.0100
[2023_06_14-16:24:03] Training the entire fine-tuned model...
[2023_06_14-16:24:20] Incompatible number of optimizer weights - will not initialize them.
Epoch 1/10
  8/468 [..............................] - ETA: 1:14:39 - loss: 0.1079

(just changed the epoch numbers so it can be done faster but its the same as 40 epochs )
 I just wanted to run the example to see the overall fine-tuning process. I don't want to override any methods or functions. How can I deal with these errors?

**Comment by r-kellerm** [comment]
@kattens - is it possible that you code isn't up to date? This is already fixed [here](https://github.com/nadavbra/protein_bert/blob/443129f062043ba44e3fdcb97ca7b47627861db0/proteinbert/model_generation.py#L33).

**Comment by kattens** [comment]
I'm not so sure where the problem is since I am basically only trying to run the exact same example in the notebook in colab. but I am still seeing the same errors.

**Comment by nadavbra** [comment]
@kattens Did you try to install the new version of ProteinBERT as @r-kellerm suggested?

**Comment by kattens** [comment]
I am following the instructions for installation:

!pip install protein-bert

then I got this:

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting protein-bert
  Downloading protein_bert-1.0.1-py3-none-any.whl (39 kB)
Requirement already satisfied: tensorflow in /usr/local/lib/python3.10/dist-packages (from protein-bert) (2.9.0)
Collecting tensorflow-addons (from protein-bert)
  Downloading tensorflow_addons-0.20.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (591 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 591.0/591.0 kB 11.0 MB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from protein-bert) (1.22.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from protein-bert) (1.5.3)
Requirement already satisfied: h5py in /usr/local/lib/python3.10/dist-packages (from protein-bert) (3.8.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from protein-bert) (4.9.2)
Collecting pyfaidx (from protein-bert)
  Downloading pyfaidx-0.7.2.1-py3-none-any.whl (28 kB)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->protein-bert) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->protein-bert) (2022.7.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from pyfaidx->protein-bert) (1.16.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from pyfaidx->protein-bert) (67.7.2)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow->protein-bert) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow->protein-bert) (1.6.3)
Requirement already satisfied: flatbuffers<2,>=1.12 in /usr/local/lib/python3.10/dist-packages (from tensorflow->protein-bert) (1.12)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow->protein-bert) (0.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow->protein-bert) (0.2.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow->protein-bert) (1.54.0)
Requirement already satisfied: keras<2.10.0,>=2.9.0rc0 in /usr/local/lib/python3.10/dist-packages (from tensorflow->protein-bert) (2.9.0)
Requirement already satisfied: keras-preprocessing>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow->protein-bert) (1.1.2)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow->protein-bert) (16.0.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow->protein-bert) (3.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow->protein-bert) (23.1)
Requirement already satisfied: protobuf>=3.9.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow->protein-bert) (3.19.6)
Requirement already satisfied: tensorboard<2.10,>=2.9 in /usr/local/lib/python3.10/dist-packages (from tensorflow->protein-bert) (2.9.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow->protein-bert) (0.32.0)
Requirement already satisfied: tensorflow-estimator<2.10.0,>=2.9.0rc0 in /usr/local/lib/python3.10/dist-packages (from tensorflow->protein-bert) (2.9.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow->protein-bert) (2.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow->protein-bert) (4.5.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow->protein-bert) (1.14.1)
Collecting typeguard<3.0.0,>=2.7 (from tensorflow-addons->protein-bert)
  Downloading typeguard-2.13.3-py3-none-any.whl (17 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow->protein-bert) (0.40.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.10,>=2.9->tensorflow->protein-bert) (2.17.3)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.10,>=2.9->tensorflow->protein-bert) (0.4.6)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.10,>=2.9->tensorflow->protein-bert) (3.4.3)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.10,>=2.9->tensorflow->protein-bert) (2.27.1)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.10,>=2.9->tensorflow->protein-bert) (0.6.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.10,>=2.9->tensorflow->protein-bert) (1.8.1)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.10,>=2.9->tensorflow->protein-bert) (2.3.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow->protein-bert) (5.3.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow->protein-bert) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow->protein-bert) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow->protein-bert) (1.3.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow->protein-bert) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow->protein-bert) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow->protein-bert) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow->protein-bert) (3.4)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.10,>=2.9->tensorflow->protein-bert) (2.1.2)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow->protein-bert) (0.5.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow->protein-bert) (3.2.2)
Installing collected packages: typeguard, pyfaidx, tensorflow-addons, protein-bert
Successfully installed protein-bert-1.0.1 pyfaidx-0.7.2.1 tensorflow-addons-0.20.0 typeguard-2.13.3


I am not quite sure if this is not the updated version.

**Comment by kattens** [comment]
I have tried that too.
but still, this error showed up:
[2023_06_16-15:15:26] Training set: Filtered out 0 of 14945 (0.0%) records of lengths exceeding 510.
[2023_06_16-15:15:27] Validation set: Filtered out 0 of 1661 (0.0%) records of lengths exceeding 510.
[2023_06_16-15:15:27] Training with frozen pretrained layers...
Epoch 1/5
468/468 [==============================] - ETA: 0s - loss: 0.0959

WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.

468/468 [==============================] - 1551s 3s/step - loss: 0.0959 - val_loss: 0.0984 - lr: 0.0100
Epoch 2/5
468/468 [==============================] - ETA: 0s - loss: 0.0729

WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.

468/468 [==============================] - 1449s 3s/step - loss: 0.0729 - val_loss: 0.0797 - lr: 0.0100
Epoch 3/5
468/468 [==============================] - ETA: 0s - loss: 0.0717

WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.

468/468 [==============================] - 1347s 3s/step - loss: 0.0717 - val_loss: 0.0691 - lr: 0.0100
Epoch 4/5
468/468 [==============================] - ETA: 0s - loss: 0.0708

WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.


Epoch 4: ReduceLROnPlateau reducing learning rate to 0.0024999999441206455.
468/468 [==============================] - 1386s 3s/step - loss: 0.0708 - val_loss: 0.0705 - lr: 0.0100
[2023_06_16-16:51:08] Training the entire fine-tuned model...
[2023_06_16-16:51:35] Incompatible number of optimizer weights - will not initialize them.

**Comment by nadavbra** [comment]
What error?

**Comment by kattens** [comment]
Epoch 4: ReduceLROnPlateau reducing learning rate to 0.0024999999441206455.
468/468 [==============================] - 1386s 3s/step - loss: 0.0708 - val_loss: 0.0705 - lr: 0.0100
[2023_06_16-16:51:08] Training the entire fine-tuned model...
[2023_06_16-16:51:35] Incompatible number of optimizer weights - will not initialize them.
Epoch 1/5
305/468 [==================>...........] - ETA: 23:33 - loss: 0.0669

**Comment by nadavbra** [comment]
It looks fine.

**Comment by kattens** [comment]
But it's not. It's in a loop that doesn't let the model train and finish. This loop continues and never ends.

**Comment by nadavbra** [comment]
What kind of loop are you talking about? Looks like the model is just training for the number of epochs it's supposed to.

**Comment by Chinjuj2017** [comment]
Hi can you help,me to resolve this error
.

467/468 [============================>.] - ETA: 0s - loss: 0.0938WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.

WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.

468/468 [==============================] - 203s 421ms/step - loss: 0.0939 - val_loss: 0.0759 - lr: 0.0100

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[28], line 46
     38 model_generator = FinetuningModelGenerator(pretrained_model_generator, OUTPUT_SPEC, pretraining_model_manipulation_function = \
     39         get_model_with_hidden_layers_as_outputs, dropout_rate = 0.5)
     41 training_callbacks = [
     42     keras.callbacks.ReduceLROnPlateau(patience = 1, factor = 0.25, min_lr = 1e-05, verbose = 1),
     43     keras.callbacks.EarlyStopping(patience = 2, restore_best_weights = True),
     44 ]
---> 46 finetune(model_generator, input_encoder, OUTPUT_SPEC, train_set['seq'], train_set['label'], valid_set['seq'], valid_set['label'], \
     47         seq_len = 512, batch_size = 32, max_epochs_per_stage = 1, lr= 1e-04, begin_with_frozen_pretrained_layers = True, \
     48         lr_with_frozen_pretrained_layers = 1e-02, n_final_epochs = 1, final_seq_len = 1024, final_lr = 1e-05, callbacks = training_callbacks)
     51 # Evaluating the performance on the test-set
     53 results, confusion_matrix = evaluate_by_len(model_generator, input_encoder, OUTPUT_SPEC, test_set['seq'], test_set['label'], \
     54         start_seq_len = 512, start_batch_size = 32)

File ~/.local/lib/python3.8/site-packages/proteinbert/finetuning.py:52, in finetune(model_generator, input_encoder, output_spec, train_seqs, train_raw_Y, valid_seqs, valid_raw_Y, seq_len, batch_size, max_epochs_per_stage, lr, begin_with_frozen_pretrained_layers, lr_with_frozen_pretrained_layers, n_final_epochs, final_seq_len, final_lr, callbacks)
     50 if begin_with_frozen_pretrained_layers:
     51     log('Training with frozen pretrained layers...')
---> 52     model_generator.train(encoded_train_set, encoded_valid_set, seq_len, batch_size, max_epochs_per_stage, lr = lr_with_frozen_pretrained_layers, \
     53             callbacks = callbacks, freeze_pretrained_layers = True)
     55 log('Training the entire fine-tuned model...')
     56 model_generator.train(encoded_train_set, encoded_valid_set, seq_len, batch_size, max_epochs_per_stage, lr = lr, callbacks = callbacks, \
     57         freeze_pretrained_layers = False)

File ~/.local/lib/python3.8/site-packages/proteinbert/model_generation.py:31, in ModelGenerator.train(self, encoded_train_set, encoded_valid_set, seq_len, batch_size, n_epochs, lr, callbacks, **create_model_kwargs)
     27     model.optimizer.lr = lr
     29 model.fit(train_X, train_Y, sample_weight = train_sample_weigths, batch_size = batch_size, epochs = n_epochs, validation_data = encoded_valid_set, \
     30         callbacks = callbacks)
---> 31 self.update_state(model)

File ~/.local/lib/python3.8/site-packages/proteinbert/model_generation.py:35, in ModelGenerator.update_state(self, model)
     33 def update_state(self, model):
     34     self.model_weights = copy_weights(model.get_weights())
---> 35     self.optimizer_weights = copy_weights(model.optimizer.get_weights())

AttributeError: 'Adam' object has no attribute 'get_weights

**Comment by nadavbra** [comment]
@Chinjuj2017 I see you already posted this issue [elsewhere](https://github.com/nadavbra/protein_bert/issues/64). Please avoid duplicate issues in the future.

**Comment by Chinjuj2017** [comment]
I am sorrry about that, i will remove the duplicate issue.
Regards,
